### ISSUE TITLE
expanding glyph functionality to detect "solid" glyph construction, i.e. the grid pattern is visible from the rear

### ISSUE THREAD

**Issue by jviguerie** [ValYouW/ArucoDetector#1]
Perhaps the concept could be called "mirrored" glyph?
Since a main motivation for aruco was built for Autonomous Navigation, I'm surprised that I haven't seen a FWD/REAR implementation. Have I missed one?
The application is interesting for marking a moving object with an inherent fwd/rear, to maintain direction vector separate from motion vector.

Anyway... Yuval, You are a Wizard. You make it look easy. By my humble eye I see:
- mod dictionary construction of signatures to add mirrored support
- mod SigEqual method to add mirrored support
- mod axis drawing method to add mirrored support
Do You have any objection if I give this a go?
Cheers,
JV. 

https://user-images.githubusercontent.com/52045567/164112420-0c03cd22-a243-4abc-97e5-ffcb8f0c41f9.mp4

**Comment by ValYouW** [comment]
Hi,

The goal of this project is educational only, to demonstrate some common image processing techniques, not trying to develop a robust Aruco detector... but feel free to fork this repo and make it your own, I won't have time to maintain this one...
Thanks

**Comment by jviguerie** [comment]
Precisely - for demo only. If it works I'll petition uco.edu or, use it in my private libs.
I Have An Offer: I want to sponsor your next Coding Notebook Vlog. $500. Implement marker "mirrored" dictionary, as described, as an increment to the Flutter & Aruco videos... for educational purposes.Venmo Zelle PayPal. Your clout, your cash, our code. hehe. 
My original vision for Gliffs (aruco sports jersey,(nine months r&d in the panel construction & field testing) was that the Rear glyph would be mirrored, to indicate body vector.But I had to back off because I wasn't ready box-break the lib. You peeled it like a grape! I'd be honored if u took this offer. Take it seriously.
JV.

    On Wednesday, April 20, 2022, 10:18:44 AM PDT, Yuval ***@***.***> wrote:  
 
 


Hi,

The goal of this project is educational only, to demonstrate some common image processing techniques, not trying to develop a robust Aruco detector... but feel free to fork this repo and make it your own, I won't have time to maintain this one...
Thanks
